-- 코드를 입력하세요
SELECT p.PRODUCT_CODE AS PRODUCT_CODE, SUM(p.PRICE*s.SALES_AMOUNT) AS SALES FROM 
    OFFLINE_SALE AS s
    JOIN
    PRODUCT AS p
    ON p.PRODUCT_ID = s.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE;