-- 코드를 입력하세요
-- 입양을 간 동물 중, 보호 기간이 가장 길었던 동물 두 마리의 아이디와 이름
SELECT ai.ANIMAL_ID AS ANIMAL_ID, ai.NAME AS NAME
--     DATEDIFF(ao.DATETIME, ai.DATETIME), ai.DATETIME, ao.DATETIME
FROM ANIMAL_INS AS ai
INNER JOIN 
ANIMAL_OUTS AS ao
ON ai.ANIMAL_ID = ao.ANIMAL_ID
ORDER BY DATEDIFF(ao.DATETIME, ai.DATETIME) DESC
LIMIT 2;