-- 코드를 입력하세요
SELECT * FROM (
    SELECT c.CAR_ID, c.CAR_TYPE, (c.DAILY_FEE*30)*(100-p.DISCOUNT_RATE) / 100 AS FEE FROM 
        CAR_RENTAL_COMPANY_CAR AS c
        LEFT JOIN (
            SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE '2022-11-01' <= END_DATE AND START_DATE <= '2022-11-30'
            GROUP BY CAR_ID
        ) AS h
        ON c.CAR_ID = h.CAR_ID
        LEFT JOIN (
            SELECT CAR_TYPE, DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
            WHERE DURATION_TYPE = '30일 이상'
        ) AS p
        ON c.CAR_TYPE = p.CAR_TYPE
    WHERE h.CAR_ID IS NULL
) AS t
WHERE 500000 <= t.FEE AND t.FEE <= 2000000
ORDER BY t.FEE DESC, t.CAR_TYPE, t.CAR_ID DESC;

    