-- 코드를 입력하세요
SELECT fg.FLAVOR FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS t FROM FIRST_HALF
    GROUP BY FLAVOR
) AS fg INNER JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS t FROM JULY
    GROUP BY FLAVOR
) AS jg
ON fg.FLAVOR = jg.FLAVOR
ORDER BY fg.t + jg.t DESC
LIMIT 3;