-- 코드를 작성해주세요
SELECT fi.ID AS ID, fni.FISH_NAME AS FISH_NAME, fi.LENGTH LENGTH FROM 
FISH_INFO AS fi
INNER JOIN 
(SELECT FISH_TYPE, MAX(LENGTH) AS ML FROM FISH_INFO 
GROUP BY FISH_TYPE) AS g
ON fi.FISH_TYPE = g.FISH_TYPE
INNER JOIN 
FISH_NAME_INFO AS fni
ON fi.FISH_TYPE  = fni.FISH_TYPE
WHERE fi.LENGTH = g.ML
ORDER BY fi.ID