-- 코드를 입력하세요
SELECT f.INGREDIENT_TYPE, SUM(f.TOTAL_ORDER) AS TOTAL_ORDER FROM (
    SELECT fh.SHIPMENT_ID, fh.TOTAL_ORDER, info.FLAVOR, info.INGREDIENT_TYPE 
    FROM FIRST_HALF AS fh
    INNER JOIN ICECREAM_INFO AS info
    ON fh.FLAVOR = info.FLAVOR
) AS f
GROUP BY f.INGREDIENT_TYPE;