-- 코드를 입력하세요
SELECT f.CATEGORY, j.MAX_PRICE, f.PRODUCT_NAME FROM 
    FOOD_PRODUCT AS f
    JOIN
    (
        SELECT PRODUCT_ID, MAX(PRICE) OVER(PARTITION BY CATEGORY) AS MAX_PRICE
        FROM FOOD_PRODUCT
    ) AS j
    ON f.PRODUCT_ID = j.PRODUCT_ID
WHERE f.CATEGORY IN('과자', '국', '김치', '식용유') AND j.MAX_PRICE = f.PRICE
ORDER BY f.PRICE DESC

/*
SELECT 
    DISTINCT(CATEGORY), 
    MAX(PRICE) OVER(PARTITION BY CATEGORY) AS MAX_PRICE
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유') 
ORDER BY PRICE DESC
*/